source 'https://rubygems.org'

ruby '2.0.0'

gem 'rake'
gem 'cocoapods',        '~> 0.24.0'
gem 'dotenv',           '~> 0.9.0'
gem 'motion-cocoapods', '~> 1.3.6'
gem 'motion-layout',    '~> 0.0.1'
gem 'motion-require',   '~> 0.0.7'
