source 'https://rubygems.org'

ruby '2.0.0'

gem 'rake'
gem 'cocoapods',        '~> 0.22.3'
gem 'dotenv',           '~> 0.8.0'
gem 'motion-cocoapods', '~> 1.3.5'
gem 'motion-layout',    '~> 0.0.1'
gem 'motion-require',   '~> 0.0.7'
